trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
 - stage: DownloadSecureFile
   jobs:
    - job: downloadJOb
      steps:
        - task: DownloadSecureFile@1
          name: public_key
          inputs:
            secureFile: 'azure_rsa.pub'

 - stage: Terraforminit
   jobs:
    - job: initJob
      variables:
        system.debug: 'true'
      steps:
        - task: TerraformCLI@2
          inputs:
            command: 'init'
            backendType: 'azurerm'
            backendServiceArm: 'Free Trial (d018c389-28e2-4236-8359-ff218fed75b2)'
            backendAzureRmTenantId: '51edc451-0ea3-422b-b556-e80cede2fdca'
            backendAzureRmSubscriptionId: 'd018c389-28e2-4236-8359-ff218fed75b2"'
            ensureBackend: true
            backendAzureRmResourceGroupName: 'backend-RG'
            backendAzureRmResourceGroupLocation: 'westeurope'
            backendAzureRmStorageAccountName: 'tfstoragename00'
            backendAzureRmContainerName: 'tfstoragename00cont'
            backendAzureRmKey: 'kubernetes-statefile'
            allowTelemetryCollection: true
        