trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
 - stage: DownloadSecureFile
   jobs:
    - job: downloadJOb
      steps:
        - task: DownloadSecureFile@1
          name: public_key
          inputs:
            secureFile: 'azure_rsa.pub'

 - stage: Terraforminit
   jobs:
    - job: initJob
      variables:
        system.debug: 'true'
      steps:
        - task: TerraformTaskV4@4
          inputs:
            provider: 'azurerm'
            command: 'init -reconfigure'
            backendServiceArm: 'azureRGSC'
            backendAzureRmResourceGroupName: 'test'
            backendAzureRmStorageAccountName: 'tfstoragename00'
            backendAzureRmContainerName: 'tfstoragename00cont'
            backendAzureRmKey: 'kubernetes-statefile'
            
 - stage: Terraform_plan
   jobs:  
     - job: PlanJob
       steps:
        - task: TerraformTaskV4@4
          inputs:
            provider: 'azurerm'
            command: 'plan'
            commandOptions: '-var client_id=$(client_id) -var client_secret=$(client_secret) -var ssh_public_key=$(public_key.secureFile)' 
            environmentServiceNameAzureRM: 'azureRGSC'
      #



