trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DownloadSecureFile@1
  name: publickey
  inputs:
    secureFile: 'azure_rsa.pub'
- bash: ls -ltr $(System.DefaultWorkingDirectory)
      

#  - stage: Terraforminit
#    jobs:
#     - job: initJob
#       steps:
#         - task: TerraformCLI@2
#           inputs:
#             command: 'init'
#             backendType: 'azurerm'
#             backendServiceArm: 'azureRGSC'
#             backendAzureRmTenantId: '51edc451-0ea3-422b-b556-e80cede2fdca'
#             backendAzureRmSubscriptionId: 'd018c389-28e2-4236-8359-ff218fed75b2'
#             ensureBackend: true
#             backendAzureRmResourceGroupName: 'backend-RG'
#             backendAzureRmResourceGroupLocation: 'westeurope'
#             backendAzureRmStorageAccountName: 'tfstoragename00'
#             backendAzureRmContainerName: 'tfstoragename00cont'
#             backendAzureRmKey: 'kubernetes-statefile'
#             allowTelemetryCollection: true
#         - task: TerraformCLI@2
#           inputs:
#             command: 'plan'
#             workingDirectory: '$(System.DefaultWorkingDirectory)'
#             environmentServiceName: 'azureRGSC'
#             commandOptions: '-var client_id=$(client_id) -var client_secret=$(client_secret) -var ssh_public_key=$(publickey.secureFilePath)'
            