trigger:
- main

pool:
  vmImage: ubuntu-latest


steps:
  - bash: echo creating AKS cluster

  - task: TerraformTaskV4@4
    inputs:
      provider: 'azurerm'
      command: 'init'
      backendServiceArm: 'azureRGSC'
      backendAzureRmResourceGroupName: 'test'
      backendAzureRmStorageAccountName: 'tfstoragename00'
      backendAzureRmContainerName: 'tfstoragename00cont'
      backendAzureRmKey: 'kubernetes-statefile'
      #



